name = "IceDrifters"
uuid = "fc3abdff-00ea-43d3-86fc-a87be9e5bb21"
authors = ["Henri Vuollekoski <henri.vuollekoski@fmi.fi> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
